---
title: "Data Import"
author: "Qimin Zhang"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read csv files
```{r, message=FALSE}
library(tidyverse)
```

## Load the litters data
```{r, message=FALSE, collapse = TRUE}
#Not to use read.csv!
litters_data = read_csv(file = "./data_import_examples//FAS_litters.csv")
#Reform the variable names
litters_data = janitor::clean_names(litters_data)
```

## Load the pups data
```{r, message=FALSE, collapse = TRUE}
pups_data = read_csv(file = "./data_import_examples//FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## Play with column parsing: define the type of viariables
```{r}
litters_data = read_csv(file = "./data_import_examples//FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```

# Read excel files
```{r}
library(readxl)
mlb11_data = read_excel("data_import_examples//mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)
```

#Read SAS files
```{r}
library(haven)
pulse_data = read_sas("./data_import_examples//public_pulse_data.sas7bdat")
head(pulse_data, 5)
```